config/routes.rb
Railslinks::Application.routes.draw do
  devise_for :users


  resources :links do
    collection do 
      get "get_title"
    end
  end

  namespace :admin do
    resources :users, :categories
    resources :links do
      member do 
        get 'validate'
        get 'unvalidate'
      end
    end
  end

  root :to => 'admin/links#index'

end

app/views/menu/_admin.html.haml
%ul.nav
  %li=link_to "Dashboard", root_path
  %li=link_to "Users", admin_users_path
  %li=link_to "Menu", admin_categories_path
%ul.nav.pull-right
  = render "menu/profile"

app/views/menu/_linker.html.haml
%ul.nav
  - @top_chapters.select{ |i| i.chapter==0}.each do |c|
    %li.dropdown{:href => "#menu#{c.id}"}
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#menu#{c.id}"}
        = c.name
        %b.caret
      =# link_to h("#{c.name}<b class='caret'></b>"), "/path3",:class=>"dropdown-toggle",:data =>{:toggle=>"dropdown"}
      %ul.dropdown-menu
        - @top_chapters.select{ |i| i.chapter==c.id}.each do |sc|
          %li= link_to sc.name, admin_categories_path(sc.name)
%ul.nav.pull-right
  %li= link_to "new Item", "#new_event_modal", :data=>{:toggle=>"modal"}
  = render "menu/profile"

app/views/menu/_menu.html.haml
%ul.nav
  - @top_chapters.select{ |i| i.chapter==0}.each do |c|
    %li.dropdown{:href => "#menu#{c.id}"}
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#menu#{c.id}"}
        = c.name
        %b.caret
      =# link_to h("#{c.name}<b class='caret'></b>"), "/path3",:class=>"dropdown-toggle",:data =>{:toggle=>"dropdown"}
      %ul.dropdown-menu
        - @top_chapters.select{ |i| i.chapter==c.id}.each do |sc|
          %li= link_to sc.name, admin_categories_path(sc.name)
%ul.nav.pull-right
  %li= link_to "Add a link", "#new_link_modal", :data=>{:toggle=>"modal"}

app/views/menu/_profile.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#menu_user"}
    = current_user.nickname.capitalize
    %b.caret
  %ul.dropdown-menu
    %li=link_to "Profile",edit_user_registration_path
    %li=link_to "Sign out",destroy_user_session_path