config/routes.rb
Railslinks::Application.routes.draw do
  devise_for :users


  resources :links do
    collection do 
      get "get_title"
    end
  end

  namespace :admin do
    resources :users, :categories
    resources :links do
      member do 
        get 'validate'
        get 'unvalidate'
      end
    end
  end

  root :to => 'admin/links#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :name, :url, :category_id, :language, :clicks
  belongs_to :category
  before_create :zero_clicks
  validates_presence_of :name, :url, :category_id
  #validates_uniqueness_of :url
  scope :validated, where(:validated=>true)
  scope :unvalidated, where(:validated=>false)
  scope :waiting, where(:validated=>nil)
  def update_click
    self.clicks += 1
    self.save!
  end


  def zero_clicks
    self.clicks = 0
  end
end

app/controllers/admin/links_controller.rb
class Admin::LinksController < Admin::ApplicationController
  load_and_authorize_resource

  def index
    @valid_links = Link.validated
    @invalid_links = Link.unvalidated
    @waiting_links = Link.waiting
  end

  def validate
    @link = Link.find(params[:id])
    @link.validated = true
    @link.save!
    redirect_to admin_links_path
  end

  def unvalidate
    @link = Link.find(params[:id])
    @link.validated = false
    @link.save!
    redirect_to admin_links_path
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  load_and_authorize_resource
  # GET /links
  # GET /links.json
  def index
    @links = Link.validated.order("created_at DESC")
    @trends_links = Link.validated.order("clicks DESC").limit(5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
    @link.update_click
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new
    @categories = Category.all.collect {|p| [ p.name, p.id ] }
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
    @categories = Category
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])
    respond_to do |format|
      if @link.save
        format.html { redirect_to links_url, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  def get_title
    duplicates = Link.where(:url=>params[:url])
    begin
      doc = Nokogiri::HTML(open params[:url])
      p doc.css('html').first.attributes["lang"]
      title = doc.css('title').inner_text.gsub(/\r\n?/, "").strip
      render :json => {url_title: title, exists:duplicates.empty?}
    rescue
      render :json => {wrong_url: true, }
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/admin/links/index.html.haml
%h1 Links
%ul.nav.nav-tabs
  %li.active
    %a{:href => "#waiting_links",:data=>{:toggle=>"tab"}} Waiting validation
  %li
    %a{:href => "#valid_links",:data=>{:toggle=>"tab"}} Valid links
  %li
    %a{:href => "#invalid_links",:data=>{:toggle=>"tab"}} Not Valid links
.tab-content
  #Waiting_links.tab-pane.active
    .row
      .span12
        %table.table.table-stripped.table-condensed
          %thead
            %tr
              %th #
              %th name
              %th Last Name
              %th Actions
          %tbody
            - @waiting_links.each do |l|
              %tr
                %td= l.id
                %td= l.name
                %td 
                  %a.btn.btn-success{:href=>"#{validate_admin_link_path(l.id)}"}
                    Validate
                  %a.btn.btn-warning{:href=>"#{unvalidate_admin_link_path(l.id)}"}
                    Unvalidate
  #valid_links.tab-pane
    .row
      .span12
        %table.table.table-stripped.table-condensed
          %thead
            %tr
              %th.span1 #
              %th.span4 name
              %th.span4 Url
              %th.span3 Actions
          %tbody
            - @valid_links.each do |l|
              %tr
                %td= l.id
                %td= l.name
                %td= l.url
                %td 
                  %a.btn.btn-success
                    Validate
                  %a.btn.btn-warning
                    Archive
                  %a.btn.btn-warning
                    Visit
  #invalid_links.tab-pane
    .row
      .span12
        %table.table.table-stripped.table-condensed
          %thead
            %tr
              %th.span1 #
              %th.span4 name
              %th.span4 Url
              %th.span3 Actions
          %tbody
            - @invalid_links.each do |l|
              %tr
                %td= l.id
                %td= l.name
                %td= l.url
                %td 
                  %a.btn.btn-success{:href=>"#{validate_admin_link_path(l.id)}"}
                    Validate
                  %a.btn.btn-warning
                    Archive
                  %a.btn.btn-warning
                    Visit