config/routes.rb
Railslinks::Application.routes.draw do
  devise_for :users


  resources :links do
    collection do 
      get "get_title"
    end
  end

  namespace :admin do
    resources :users, :categories
    resources :links do
      member do 
        get 'validate'
        get 'unvalidate'
      end
    end
  end

  root :to => 'admin/links#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :chapter, :name
  has_many :links

  def define_chapter
    self.clicks = 0
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  load_and_authorize_resource
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.where(:name => params[:id]).first
    @links = Link.where(:category_id => @category.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    @chapters = Category.where(:chapter => 0).collect {|p| [ p.name, p.id ] }
    p @chapters
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    @chapters = Category.where(:chapter => 0).collect {|p| [ p.name, p.id ] }
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    @category.chapter = 0 if params[:is_chapter]
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_url
  end
end

app/views/admin/categories/_form.html.haml
= form_for([:admin,@category]) do |f|
  - if @category.errors.any?
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = label_tag :is_chapter
    %br/
    = check_box_tag :is_chapter
  .field#cat_select
    = f.label :chapter
    %br/
    = f.select :chapter, options_for_select(@chapters), {:include_blank => '-----'}
  .actions
    = f.submit

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th Name
    %th Chapter
    %th
    %th
    %th
  - @categories.each do |category|
    - if category.chapter==0
      %tr.chapter
    - else
      %tr.sub-chapter
    %td= category.name
%br/
%ul.chapters-listing
  - @categories.select{ |i| i.chapter==0}.each do |c|
    %li.dropdown{:href => "#menu#{c.id}"}
      %h3= c.name
      (
      = link_to 'Edit', edit_admin_category_path(c)
      = link_to 'Destroy', admin_category_path(c), confirm: 'Are you sure?', method: :delete
      )
      %ul.sub-chapters-listing
        - @categories.select{ |i| i.chapter==c.id}.each do |sc|
          %li
            = link_to sc.name, admin_categories_path(sc.name)
            .actionOnCat
              = link_to 'Edit', edit_admin_category_path(sc)
              = link_to 'Destroy', admin_category_path(sc), confirm: 'Are you sure?', method: :delete


= link_to 'New Category', new_admin_category_path

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

app/views/admin/categories/show.html.haml
%p#notice= notice
%h1= @category.name.capitalize
%table.table.table-condensed.table-stripped
  %thead
    %tr
      %th Name
      %th Url
  %tbody
    - @links.each do |l|
      %tr
        %td= l.name
        %td= link_to l.url
= link_to 'Edit', edit_category_path(@category)
|
\#{link_to 'Back', categories_path}